// Generated by scripts/freeciv/generate_event_types.py. DO NOT EDIT.
// Source: schemas/freeciv-events/v1/*.schema.json

export const EVENT_SCHEMA_VERSION = "1.0" as const;

export type JsonValue = null | boolean | number | string | unknown[] | Record<string, unknown>;

export type TruthValue = {
  "confidence": number;
  "strength": number;
};

export type ObservationPolicy = {
  "channel": "observe";
  "goal_id": string;
  "priority": number;
  "propensity": number | null;
};

export type ModelProvenance = {
  "confidence_cap": number;
  "exact": boolean;
  "model_hash": string;
  "model_id": string;
  "model_version": string;
  "source_kind": "simulator";
};

export type Atom = {
  "args": Array<JsonValue>;
  "atom_id": string;
  "crisp": boolean;
  "predicate": string;
  "provenance_ids": Array<string>;
  "tv": TruthValue;
};

export type ProofNode = {
  "atom": Atom;
  "crisp": boolean;
  "dampening_lambda"?: number | null;
  "formula"?: Record<string, unknown> | null;
  "grounded_result"?: JsonValue;
  "kind": "goal" | "and" | "or" | "premise" | "grounded" | "cycle" | "unreachable";
  "node_id": string;
  "premise_node_refs": Array<string>;
  "rule_applied": string | null;
  "rule_source"?: Record<string, unknown> | null;
  "satisfied": boolean;
  "scope"?: JsonValue;
  "subtree_hash": string;
  "tv": TruthValue;
};

export type ProofTree = {
  "nodes": Array<ProofNode>;
  "root_node_id": string;
  "structural_hash": string;
};

export type FrontierItem = {
  "atom_id": string;
  "blocker_type": "missing-tech" | "missing-building" | "grounded-predicate" | "disabled-goal" | "cycle" | "unreachable";
  "detail": string;
  "node_id": string;
};

export type Assumption = {
  "accepted_tv": TruthValue;
  "affected_step_ids": Array<string>;
  "atom_id": string;
  "proof_node_id"?: string | null;
  "provenance_ids"?: Array<string>;
  "subtree_hash"?: string | null;
  "threshold": number;
};

export type PlanStep = {
  "actual_turn": number | null;
  "cost": number;
  "duration_turns"?: number;
  "kind": string;
  "legal_actions_digest"?: string | null;
  "predicted_turn": number;
  "snapshot_id"?: string | null;
  "spatial": Record<string, unknown> | null;
  "status": "PENDING" | "ACTIVE" | "COMPLETED" | "FAILED" | "CANCELLED";
  "step_id": string;
  "target": JsonValue;
};

export type LedgerEntry = {
  "allocated": number;
  "available": number;
  "remaining": number;
  "resource": string;
  "step_id": string;
};

export type Plan = {
  "assumptions": Array<Assumption>;
  "branch_scores"?: Array<{
    "branch_id": string;
    "feasibility_grade": number;
    "feasible": boolean;
    "predicted_turns": number;
    "reason": string | null;
    "scheduler_cost": number;
  }>;
  "cost_profile": string;
  "feasibility_grade": number;
  "goal_atom_id": string;
  "ledger": Array<LedgerEntry>;
  "plan_id": string;
  "predicted_turns"?: number;
  "rederived_subtree_hashes"?: Array<string>;
  "reused_subtree_hashes"?: Array<string>;
  "scheduler_cost": number;
  "schema_version"?: string;
  "selected_branch_id"?: string;
  "snapshot_id": string;
  "solver_identity"?: string;
  "source_proof_hash": string;
  "status": "ACTIVE" | "COMPLETED" | "INVALID" | "FAILED";
  "steps": Array<PlanStep>;
};

export type RunStarted = {
  "condition_id": string;
  "manifest_identity": string;
};

export type RunCompleted = {
  "status": "completed" | "failed" | "aborted";
  "summary": {
    [key: string]: unknown;
  };
};

export type RulesetCompiled = {
  "atomese_hash": string;
  "counts": {
    [key: string]: number;
  };
  "ir_hash": string;
  "ruleset": string;
  "source_hash": string;
};

export type StateSnapshot = {
  "legal_actions_digest"?: string;
  "map": {
    [key: string]: unknown;
  };
  "own_state": {
    [key: string]: unknown;
  };
  "player_id": number;
  "snapshot_id": string;
  "source_seq"?: number;
  "state_hash": string;
  "uncertain_atoms": Array<Atom>;
};

export type Observation = {
  "age_turns": number;
  "atom": Atom;
  "model_provenance"?: ModelProvenance;
  "observation_id": string;
  "provenance_id": string;
  "selection_policy"?: ObservationPolicy;
  "source": string;
};

export type Revision = {
  "evidence_tv": TruthValue;
  "formula": {
    "inputs": {
      [key: string]: unknown;
    };
    "name": string;
    [key: string]: unknown;
  };
  "operation": "apply" | "decay" | "retract";
  "posterior_tv": TruthValue;
  "prior_tv": TruthValue | null;
  "provenance_id": string;
  "target_atom": Atom;
};

export type BeliefConflict = {
  "conflict_atom": Atom;
  "conflict_id": string;
  "context_ids": Array<string>;
  "detected_turn": number;
  "left_provenance_ids": Array<string>;
  "left_tv": TruthValue;
  "overlap": number;
  "right_provenance_ids": Array<string>;
  "right_tv": TruthValue;
  "severity": number;
  "target_atom_id": string;
};

export type ContextQuarantine = {
  "conflict_id": string;
  "context_id": string;
  "excluded_provenance_ids": Array<string>;
  "operation_id": string;
  "reason": string;
  "retained_provenance_ids": Array<string>;
  "target_atom_id": string;
  "turn": number;
};

export type LlmProposal = {
  "claims": Array<{
    "atom": Atom | null;
    "claim_id": string;
    "text": string;
  }>;
  "goals": Array<{
    [key: string]: unknown;
  }>;
  "model": string;
  "prompt_version": string;
  "proposal_id": string;
};

export type Verification = {
  "check": string;
  "claim_id": string;
  "evidence_atom_ids": Array<string>;
  "proposal_id": string;
  "verdict": "believe" | "disbelieve" | "quarantine";
  "verification_id": string;
};

export type Quarantine = {
  "claim": string;
  "claim_id": string;
  "evidence_atoms": Array<Atom>;
  "failed_check": string;
  "model"?: string;
  "model_config"?: {
    [key: string]: JsonValue;
  };
  "proposal_id": string;
  "quarantine_id": string;
  "quarantined_at"?: string;
};

export type PlnQuery = {
  "invoking_layer": "llm-verification" | "planner" | "monitor" | "state-oracle" | "test";
  "query_atom": Atom;
  "query_id": string;
  "query_type": "deps" | "verify" | "grade";
};

export type PlnResult = {
  "cache_status"?: "hit" | "miss" | "error";
  "chain_depth": number;
  "dampening_lambda": number | null;
  "error"?: Record<string, unknown> | null;
  "latency_ms": number;
  "prerequisite_atoms"?: Array<Atom>;
  "proof": ProofTree;
  "query_id": string;
  "status": "PROVED" | "BLOCKED" | "UNREACHABLE" | "ERROR";
  "tree_size"?: number;
  "unsatisfied_frontier": Array<FrontierItem>;
};

export type PressurePropagated = {
  "conductance_state"?: Record<string, unknown> | null;
  "config": {
    [key: string]: unknown;
  };
  "dependency": {
    [key: string]: unknown;
  };
  "goals": Array<{
    [key: string]: unknown;
  }>;
  "graph_hash": string;
  "operational_pressure": {
    [key: string]: unknown;
  };
  "pressure_id": string;
  "result_hash": string;
  "traces": Array<{
    [key: string]: unknown;
  }>;
};

export type OperationScored = {
  "allocations": Array<{
    [key: string]: unknown;
  }>;
  "decision_id": string;
  "pressure_id": string;
  "scores": Array<{
    [key: string]: unknown;
  }>;
  "selected_operation_id": string | null;
  "solver_identity": string;
  "structural_hash": string;
};

export type ConductanceUpdated = {
  "applied": boolean;
  "category": string;
  "caused_by_feedback_id"?: string;
  "conductance": number;
  "credit_kind"?: "no_progress" | "effect_without_goal_relief" | "direct_goal_relief" | "downstream_goal_relief";
  "effect_observed": boolean;
  "feedback_id": string;
  "learning_method": "grounded-effect-ema-v1" | "grounded-goal-relief-ema-v2";
  "no_progress": number;
  "no_progress_amount"?: number;
  "previous_conductance": number;
  "realized_relief"?: number;
  "relief_source"?: string;
  "rule_id": string;
  "state_hash": string;
  "successes": number;
};

export type PlanCreated = {
  "plan": Plan;
};

export type MonitorTrigger = {
  "affected_plan_ids": Array<string>;
  "atom_id": string;
  "posterior_tv": TruthValue;
  "prior_tv": TruthValue;
  "threshold": number;
  "trigger_id": string;
};

export type PlanInvalidated = {
  "affected_step_ids": Array<string>;
  "broken_assumption": Assumption;
  "broken_assumptions"?: Array<Assumption>;
  "plan_id": string;
  "posterior_tv"?: TruthValue;
  "prior_tv"?: TruthValue;
  "reason": string;
  "rederived_subtree_hashes": Array<string>;
  "reused_subtree_hashes": Array<string>;
  "revision_event_ids"?: Array<string>;
};

export type PlanStepExecuted = {
  "plan_id": string;
  "snapshot_id": string;
  "status": "started" | "completed" | "failed" | "rejected";
  "step_id": string;
};

export type ActionSent = {
  "action": {
    [key: string]: unknown;
  };
  "action_id": string;
  "legal_actions_digest": string;
  "plan_id": string | null;
  "snapshot_id": string;
  "step_id": string | null;
};

export type ActionResult = {
  "action_id": string;
  "engine_response": JsonValue;
  "engine_turn": number;
  "status": "accepted" | "rejected" | "timeout" | "unknown";
};

export type GroundedCheck = {
  "args": Array<JsonValue>;
  "available"?: boolean;
  "check_id": string;
  "diagnostic": string | null;
  "predicate": string;
  "satisfied": boolean;
  "snapshot_id": string;
  "value": JsonValue;
};

export type MetricSample = {
  "labels": {
    [key: string]: string;
  };
  "name": string;
  "unit": string;
  "value": number;
};

export type LoggingGap = {
  "component": string;
  "detail": string;
  "missing": string;
};

export type KnownEventType = "run_started" | "run_completed" | "ruleset_compiled" | "state_snapshot" | "observation" | "revision" | "belief_conflict" | "context_quarantine" | "llm_proposal" | "verification" | "quarantine" | "pln_query" | "pln_result" | "pressure_propagated" | "operation_scored" | "conductance_updated" | "plan_created" | "monitor_trigger" | "plan_invalidated" | "plan_step_executed" | "action_sent" | "action_result" | "grounded_check" | "metric_sample" | "logging_gap";

export interface EventEnvelope<T extends string = string, P extends object = Record<string, unknown>> {
  schema_version: typeof EVENT_SCHEMA_VERSION;
  event_id: string;
  game_id: string;
  turn: number;
  seq: number;
  ts: string;
  type: T;
  caused_by: string[];
  payload: P;
}

export interface KnownPayloadMap {
  "run_started": RunStarted;
  "run_completed": RunCompleted;
  "ruleset_compiled": RulesetCompiled;
  "state_snapshot": StateSnapshot;
  "observation": Observation;
  "revision": Revision;
  "belief_conflict": BeliefConflict;
  "context_quarantine": ContextQuarantine;
  "llm_proposal": LlmProposal;
  "verification": Verification;
  "quarantine": Quarantine;
  "pln_query": PlnQuery;
  "pln_result": PlnResult;
  "pressure_propagated": PressurePropagated;
  "operation_scored": OperationScored;
  "conductance_updated": ConductanceUpdated;
  "plan_created": PlanCreated;
  "monitor_trigger": MonitorTrigger;
  "plan_invalidated": PlanInvalidated;
  "plan_step_executed": PlanStepExecuted;
  "action_sent": ActionSent;
  "action_result": ActionResult;
  "grounded_check": GroundedCheck;
  "metric_sample": MetricSample;
  "logging_gap": LoggingGap;
}

export type KnownEvent = {
  [K in KnownEventType]: EventEnvelope<K, KnownPayloadMap[K]>;
}[KnownEventType];

export type UnknownEvent = EventEnvelope<string, Record<string, unknown>>;
export type FreecivEvent = KnownEvent | UnknownEvent;
