// Generated by scripts/freeciv/generate_event_types.py. DO NOT EDIT.
// Source: schemas/freeciv-events/v1/*.schema.json

export const EVENT_SCHEMA_VERSION = "1.0" as const;

export type JsonValue = null | boolean | number | string | unknown[] | Record<string, unknown>;

export type TruthValue = {
  "confidence": number;
  "strength": number;
};

export type ObservationPolicy = {
  "channel": "observe";
  "goal_id": string;
  "priority": number;
  "propensity": number | null;
};

export type ModelProvenance = {
  "confidence_cap": number;
  "exact": boolean;
  "model_hash": string;
  "model_id": string;
  "model_version": string;
  "source_kind": "simulator";
};

export type Atom = {
  "args": Array<JsonValue>;
  "atom_id": string;
  "crisp": boolean;
  "predicate": string;
  "provenance_ids": Array<string>;
  "tv": TruthValue;
};

export type ProofNode = {
  "atom": Atom;
  "crisp": boolean;
  "dampening_lambda"?: number | null;
  "formula"?: Record<string, unknown> | null;
  "grounded_result"?: JsonValue;
  "kind": "goal" | "and" | "or" | "premise" | "grounded" | "cycle" | "unreachable";
  "node_id": string;
  "premise_node_refs": Array<string>;
  "rule_applied": string | null;
  "rule_source"?: Record<string, unknown> | null;
  "satisfied": boolean;
  "scope"?: JsonValue;
  "subtree_hash": string;
  "tv": TruthValue;
};

export type ProofTree = {
  "nodes": Array<ProofNode>;
  "root_node_id": string;
  "structural_hash": string;
};

export type FrontierItem = {
  "atom_id": string;
  "blocker_type": "missing-tech" | "missing-building" | "grounded-predicate" | "disabled-goal" | "cycle" | "unreachable";
  "detail": string;
  "node_id": string;
};

export type Assumption = {
  "accepted_tv": TruthValue;
  "affected_step_ids": Array<string>;
  "atom_id": string;
  "proof_node_id"?: string | null;
  "provenance_ids"?: Array<string>;
  "subtree_hash"?: string | null;
  "threshold": number;
};

export type PlanStep = {
  "actual_turn": number | null;
  "cost": number;
  "duration_turns"?: number;
  "kind": string;
  "legal_actions_digest"?: string | null;
  "predicted_turn": number;
  "snapshot_id"?: string | null;
  "spatial": Record<string, unknown> | null;
  "status": "PENDING" | "ACTIVE" | "COMPLETED" | "FAILED" | "CANCELLED";
  "step_id": string;
  "target": JsonValue;
};

export type LedgerEntry = {
  "allocated": number;
  "available": number;
  "remaining": number;
  "resource": string;
  "step_id": string;
};

export type Plan = {
  "assumptions": Array<Assumption>;
  "branch_scores"?: Array<{
    "branch_id": string;
    "feasibility_grade": number;
    "feasible": boolean;
    "predicted_turns": number;
    "reason": string | null;
    "scheduler_cost": number;
  }>;
  "cost_profile": string;
  "feasibility_grade": number;
  "goal_atom_id": string;
  "ledger": Array<LedgerEntry>;
  "plan_id": string;
  "predicted_turns"?: number;
  "rederived_subtree_hashes"?: Array<string>;
  "reused_subtree_hashes"?: Array<string>;
  "scheduler_cost": number;
  "schema_version"?: string;
  "selected_branch_id"?: string;
  "snapshot_id": string;
  "solver_identity"?: string;
  "source_proof_hash": string;
  "status": "ACTIVE" | "COMPLETED" | "INVALID" | "FAILED";
  "steps": Array<PlanStep>;
};

export type RunStarted = {
  "condition_id": string;
  "manifest_identity": string;
};

export type RunCompleted = {
  "status": "completed" | "failed" | "aborted";
  "summary": {
    [key: string]: unknown;
  };
};

export type RulesetCompiled = {
  "atomese_hash": string;
  "counts": {
    [key: string]: number;
  };
  "ir_hash": string;
  "ruleset": string;
  "source_hash": string;
};

export type StateSnapshot = {
  "legal_actions_digest"?: string;
  "map": {
    [key: string]: unknown;
  };
  "own_state": {
    [key: string]: unknown;
  };
  "player_id": number;
  "snapshot_id": string;
  "source_seq"?: number;
  "state_hash": string;
  "uncertain_atoms": Array<Atom>;
};

export type TechnologyCatalogEntry = {
  "name": string;
  "prerequisites": Array<string>;
  "rule_id": string;
  "source"?: {
    [key: string]: JsonValue;
  };
};

export type TechnologyBlocker = {
  "missing_prerequisites": Array<string>;
  "name": string;
};

export type ResearchTarget = {
  "beakers_per_turn": number | null;
  "cost": number | null;
  "eta_turns": number | null;
  "id": number | null;
  "name": string;
  "progress": number | null;
  "remaining": number | null;
};

export type TechnologyCatalog = {
  "catalog_id": string;
  "ir_hash": string;
  "ruleset": string;
  "technologies": Array<TechnologyCatalogEntry>;
};

export type TechnologyProgress = {
  "acquired_techs": Array<string>;
  "available": boolean;
  "blocked_technologies": Array<TechnologyBlocker>;
  "diagnostic"?: string | null;
  "government"?: GovernmentState;
  "known_techs": Array<string>;
  "researchable_techs": Array<string>;
  "snapshot_id": string;
  "stall_reason"?: "government_anarchy" | "city_disorder" | "zero_science_output" | "research_progress_not_advancing" | null;
  "stalled_turns": number;
  "status": "unavailable" | "idle" | "researching" | "stalled" | "complete";
  "target": ResearchTarget | null;
};

export type GovernmentState = {
  "available": boolean;
  "current_id": number | null;
  "current_name": string | null;
  "diagnostic": string | null;
  "in_revolution": boolean;
  "revolution_finishes": number | null;
  "selection_required": boolean;
  "target_id": number | null;
  "target_name": string | null;
};

export type YieldVector = {
  "food": number | null;
  "gold": number | null;
  "luxury": number | null;
  "science": number | null;
  "shield": number | null;
  "trade": number | null;
};

export type ProductionTarget = {
  "kind": number | null;
  "name": string | null;
  "value": number | null;
};

export type CityProductionState = {
  "buildable_count": number;
  "building_changes"?: Array<BuildingChange>;
  "building_upkeep"?: number;
  "buildings"?: Array<CityBuilding>;
  "city_id": number;
  "food_stock": number | null;
  "governor"?: CityGovernor;
  "had_famine"?: boolean | null;
  "mood"?: CityMood;
  "name": string;
  "outputs": YieldVector;
  "shield_stock": number | null;
  "size": number;
  "support"?: CitySupport;
  "surplus": YieldVector;
  "target": ProductionTarget;
  "usage"?: YieldVector;
};

export type CityBuilding = {
  "improvement_id": number;
  "name": string;
  "upkeep": number | null;
};

export type BuildingChange = {
  "improvement_id": number;
  "name": string;
  "transition": "completed" | "removed";
  "upkeep": number | null;
};

export type CityGovernor = {
  "allow_disorder": boolean | null;
  "allow_specialists": boolean | null;
  "available": boolean;
  "enabled": boolean | null;
  "factor": Array<number>;
  "happy_factor": number | null;
  "max_growth": boolean | null;
  "minimal_surplus": Array<number>;
  "require_happy": boolean | null;
};

export type CitizenFeeling = {
  "angry": number | null;
  "content": number | null;
  "happy": number | null;
  "unhappy": number | null;
};

export type CityMood = {
  "disorder": boolean | null;
  "final": CitizenFeeling;
  "margin": number | null;
  "stages": {
    "angry": Array<number>;
    "content": Array<number>;
    "happy": Array<number>;
    "unhappy": Array<number>;
  };
  "was_happy": boolean | null;
};

export type CitySupport = {
  "count": number;
  "food": number;
  "gold": number;
  "shield": number;
};

export type ProductionEconomy = {
  "available": boolean;
  "capitalization_gold_per_turn"?: number | null;
  "city_gold_surplus_per_turn"?: number | null;
  "diagnostic"?: string | null;
  "gold": number | null;
  "gold_per_turn": number | null;
  "gold_upkeep_reserve"?: number | null;
  "gold_upkeep_style"?: "City" | "Mixed" | "Nation" | null;
  "luxury_rate": number | null;
  "operating_gold_per_turn"?: number | null;
  "science_rate": number | null;
  "tax_rate": number | null;
  "unit_gold_upkeep"?: number | null;
};

export type ResearchFlow = {
  "gross_beakers_per_turn": number | null;
  "net_beakers_per_turn": number | null;
  "tech_upkeep": number | null;
};

export type PlayerScore = {
  "is_alive": boolean | null;
  "name": string;
  "player_id": number;
  "score": number | null;
};

export type ScoreState = {
  "gap_to_leader": number | null;
  "leader": PlayerScore | null;
  "opponents": Array<PlayerScore>;
  "own": number | null;
};

export type ProductionState = {
  "cities": Array<CityProductionState>;
  "economy": ProductionEconomy;
  "government"?: GovernmentState;
  "research_flow"?: ResearchFlow;
  "score"?: ScoreState;
  "snapshot_id": string;
};

export type UnitLifecycle = {
  "cause": "initial_state" | "observed_appearance" | "production_completed" | "city_founded" | "combat_attacker_lost" | "combat_defender_lost" | "combat_stack_collateral" | "transport_lost" | "upkeep_gold" | "upkeep_food" | "engine_removed" | "unknown_turn_boundary";
  "detail"?: string | null;
  "evidence_event_ids": Array<string>;
  "evidence_quality": "exact" | "inferred" | "unattributed";
  "from_snapshot_id": string | null;
  "last_position"?: Record<string, unknown> | null;
  "lifecycle_id": string;
  "to_snapshot_id": string | null;
  "transition": "appeared" | "disappeared";
  "unit_id": number;
  "unit_type": string;
};

export type Observation = {
  "age_turns": number;
  "atom": Atom;
  "model_provenance"?: ModelProvenance;
  "observation_id": string;
  "provenance_id": string;
  "selection_policy"?: ObservationPolicy;
  "source": string;
};

export type Revision = {
  "evidence_tv": TruthValue;
  "formula": {
    "inputs": {
      [key: string]: unknown;
    };
    "name": string;
    [key: string]: unknown;
  };
  "operation": "apply" | "decay" | "retract";
  "posterior_tv": TruthValue;
  "prior_tv": TruthValue | null;
  "provenance_id": string;
  "target_atom": Atom;
};

export type BeliefConflict = {
  "conflict_atom": Atom;
  "conflict_id": string;
  "context_ids": Array<string>;
  "detected_turn": number;
  "left_provenance_ids": Array<string>;
  "left_tv": TruthValue;
  "overlap": number;
  "right_provenance_ids": Array<string>;
  "right_tv": TruthValue;
  "severity": number;
  "target_atom_id": string;
};

export type ContextQuarantine = {
  "conflict_id": string;
  "context_id": string;
  "excluded_provenance_ids": Array<string>;
  "operation_id": string;
  "reason": string;
  "retained_provenance_ids": Array<string>;
  "target_atom_id": string;
  "turn": number;
};

export type LlmProposal = {
  "claims": Array<{
    "atom": Atom | null;
    "claim_id": string;
    "text": string;
  }>;
  "goals": Array<{
    [key: string]: unknown;
  }>;
  "model": string;
  "prompt_version": string;
  "proposal_id": string;
};

export type GoalSelection = {
  "candidate_count": 1;
  "goal": {
    "arguments": Array<string | number>;
    "goal_id": string;
    "predicate": "researchable" | "buildable";
    "target_id": string;
  };
  "model_call_avoided": true;
  "policy": "canonical-singleton-bypass-v1";
  "proposal_id": string;
  "selection_id": string;
  "source": "canonical_catalog";
};

export type Verification = {
  "check": string;
  "claim_id": string;
  "evidence_atom_ids": Array<string>;
  "proposal_id": string;
  "verdict": "believe" | "disbelieve" | "quarantine";
  "verification_id": string;
};

export type Quarantine = {
  "claim": string;
  "claim_id": string;
  "evidence_atoms": Array<Atom>;
  "failed_check": string;
  "model"?: string;
  "model_config"?: {
    [key: string]: JsonValue;
  };
  "proposal_id": string;
  "quarantine_id": string;
  "quarantined_at"?: string;
};

export type PlnQuery = {
  "invoking_layer": "llm-verification" | "planner" | "monitor" | "state-oracle" | "test";
  "query_atom": Atom;
  "query_id": string;
  "query_type": "deps" | "verify" | "grade";
};

export type PlnResult = {
  "cache_status"?: "hit" | "miss" | "error";
  "chain_depth": number;
  "dampening_lambda": number | null;
  "error"?: Record<string, unknown> | null;
  "latency_ms": number;
  "prerequisite_atoms"?: Array<Atom>;
  "proof": ProofTree;
  "query_id": string;
  "status": "PROVED" | "BLOCKED" | "UNREACHABLE" | "ERROR";
  "tree_size"?: number;
  "unsatisfied_frontier": Array<FrontierItem>;
};

export type PressurePropagated = {
  "conductance_state"?: Record<string, unknown> | null;
  "config": {
    [key: string]: unknown;
  };
  "dependency": {
    [key: string]: unknown;
  };
  "goals": Array<{
    [key: string]: unknown;
  }>;
  "graph_hash": string;
  "operational_pressure": {
    [key: string]: unknown;
  };
  "pressure_id": string;
  "result_hash": string;
  "traces": Array<{
    [key: string]: unknown;
  }>;
};

export type OperationScored = {
  "allocations": Array<{
    [key: string]: unknown;
  }>;
  "decision_id": string;
  "pressure_id": string;
  "scores": Array<{
    [key: string]: unknown;
  }>;
  "selected_operation_id": string | null;
  "solver_identity": string;
  "structural_hash": string;
};

export type ConductanceUpdated = {
  "applied": boolean;
  "category": string;
  "caused_by_feedback_id"?: string;
  "conductance": number;
  "credit_kind"?: "no_progress" | "effect_without_goal_relief" | "direct_goal_relief" | "downstream_goal_relief";
  "effect_observed": boolean;
  "feedback_id": string;
  "learning_method": "grounded-effect-ema-v1" | "grounded-goal-relief-ema-v2";
  "no_progress": number;
  "no_progress_amount"?: number;
  "previous_conductance": number;
  "realized_relief"?: number;
  "relief_source"?: string;
  "rule_id": string;
  "state_hash": string;
  "successes": number;
};

export type RuleProposed = {
  "expansion": {
    "accepted": true;
    "expand_pressure": number;
    "expected_value": number;
    "operation": {
      [key: string]: unknown;
    };
    "reason": null;
    "validation_cost": number;
  };
  "ledger_hash": string;
  "lifecycle": "quarantined";
  "proposal": {
    [key: string]: unknown;
  };
  "proposal_id": string;
};

export type RuleValidated = {
  "ledger_hash": string;
  "metrics": {
    "activations": number;
    "baseline_brier": number;
    "baseline_calibration_error": number;
    "baseline_contradiction_rate": number;
    "baseline_log_loss": number;
    "brier_improvement": number;
    "calibration_improvement": number;
    "candidate_brier": number;
    "candidate_calibration_error": number;
    "candidate_contradiction_rate": number;
    "candidate_log_loss": number;
    "samples": number;
  };
  "proposal_id": string;
  "reason": string;
  "validation_id": string;
  "verdict": "promoted" | "demoted";
};

export type LlmCallScheduled = {
  "decision": {
    "accepted": boolean;
    "call_id": string;
    "expand_pressure": number;
    "operation": Record<string, unknown> | null;
    "quality": number;
    "reason": string | null;
    "request": {
      [key: string]: unknown;
    };
    "total_cost": number;
  };
  "ledger_hash": string;
};

export type LlmGatewayResult = {
  "call_id": string;
  "charged_tokens": number;
  "envelope": Record<string, unknown> | null;
  "error": string | null;
  "ledger_hash": string;
  "status": "quarantined_pending_validation" | "quarantined" | "rejected" | "failed";
};

export type RuleParameterUpdated = {
  "examples": number;
  "gradient": number;
  "learning_rate": number;
  "method": "reverse-mode-mse-v1";
  "parameter_id": string;
  "posterior_loss": number;
  "prior_loss": number;
  "prior_value": number;
  "update_id": string;
  "value": number;
};

export type PlanCreated = {
  "plan": Plan;
};

export type MonitorTrigger = {
  "affected_plan_ids": Array<string>;
  "atom_id": string;
  "posterior_tv": TruthValue;
  "prior_tv": TruthValue;
  "threshold": number;
  "trigger_id": string;
};

export type PlanInvalidated = {
  "affected_step_ids": Array<string>;
  "broken_assumption": Assumption;
  "broken_assumptions"?: Array<Assumption>;
  "plan_id": string;
  "posterior_tv"?: TruthValue;
  "prior_tv"?: TruthValue;
  "reason": string;
  "rederived_subtree_hashes": Array<string>;
  "reused_subtree_hashes": Array<string>;
  "revision_event_ids"?: Array<string>;
};

export type PlanStepExecuted = {
  "plan_id": string;
  "snapshot_id": string;
  "status": "started" | "completed" | "failed" | "rejected";
  "step_id": string;
};

export type ActionSent = {
  "action": {
    [key: string]: unknown;
  };
  "action_id": string;
  "legal_actions_digest": string;
  "plan_id": string | null;
  "snapshot_id": string;
  "step_id": string | null;
};

export type ActionResult = {
  "action_id": string;
  "engine_response": JsonValue;
  "engine_turn": number;
  "status": "accepted" | "rejected" | "timeout" | "unknown";
};

export type GroundedCheck = {
  "args": Array<JsonValue>;
  "available"?: boolean;
  "check_id": string;
  "diagnostic": string | null;
  "predicate": string;
  "satisfied": boolean;
  "snapshot_id": string;
  "value": JsonValue;
};

export type MetricSample = {
  "labels": {
    [key: string]: string;
  };
  "name": string;
  "unit": string;
  "value": number;
};

export type LoggingGap = {
  "component": string;
  "detail": string;
  "missing": string;
};

export type KnownEventType = "run_started" | "run_completed" | "ruleset_compiled" | "state_snapshot" | "technology_catalog" | "technology_progress" | "production_state" | "unit_lifecycle" | "observation" | "revision" | "belief_conflict" | "context_quarantine" | "llm_proposal" | "goal_selection" | "verification" | "quarantine" | "pln_query" | "pln_result" | "pressure_propagated" | "operation_scored" | "conductance_updated" | "rule_proposed" | "rule_validated" | "llm_call_scheduled" | "llm_gateway_result" | "rule_parameter_updated" | "plan_created" | "monitor_trigger" | "plan_invalidated" | "plan_step_executed" | "action_sent" | "action_result" | "grounded_check" | "metric_sample" | "logging_gap";

export interface EventEnvelope<T extends string = string, P extends object = Record<string, unknown>> {
  schema_version: typeof EVENT_SCHEMA_VERSION;
  event_id: string;
  game_id: string;
  turn: number;
  seq: number;
  ts: string;
  type: T;
  caused_by: string[];
  payload: P;
}

export interface KnownPayloadMap {
  "run_started": RunStarted;
  "run_completed": RunCompleted;
  "ruleset_compiled": RulesetCompiled;
  "state_snapshot": StateSnapshot;
  "technology_catalog": TechnologyCatalog;
  "technology_progress": TechnologyProgress;
  "production_state": ProductionState;
  "unit_lifecycle": UnitLifecycle;
  "observation": Observation;
  "revision": Revision;
  "belief_conflict": BeliefConflict;
  "context_quarantine": ContextQuarantine;
  "llm_proposal": LlmProposal;
  "goal_selection": GoalSelection;
  "verification": Verification;
  "quarantine": Quarantine;
  "pln_query": PlnQuery;
  "pln_result": PlnResult;
  "pressure_propagated": PressurePropagated;
  "operation_scored": OperationScored;
  "conductance_updated": ConductanceUpdated;
  "rule_proposed": RuleProposed;
  "rule_validated": RuleValidated;
  "llm_call_scheduled": LlmCallScheduled;
  "llm_gateway_result": LlmGatewayResult;
  "rule_parameter_updated": RuleParameterUpdated;
  "plan_created": PlanCreated;
  "monitor_trigger": MonitorTrigger;
  "plan_invalidated": PlanInvalidated;
  "plan_step_executed": PlanStepExecuted;
  "action_sent": ActionSent;
  "action_result": ActionResult;
  "grounded_check": GroundedCheck;
  "metric_sample": MetricSample;
  "logging_gap": LoggingGap;
}

export type KnownEvent = {
  [K in KnownEventType]: EventEnvelope<K, KnownPayloadMap[K]>;
}[KnownEventType];

export type UnknownEvent = EventEnvelope<string, Record<string, unknown>>;
export type FreecivEvent = KnownEvent | UnknownEvent;
