#!/usr/bin/env python3
"""Generate strict TypeScript event types from the V0 JSON Schemas.

This intentionally supports the JSON Schema constructs used by our published
schemas. Unsupported constructs fail generation instead of silently widening a
type. The resulting file is checked in so the replay UI can compile without a
Python build step, but it must remain byte-identical to this generator's output.
"""

import argparse
import json
import os
import re
import sys


_REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_SCHEMA_DIR = os.path.join(_REPO, "schemas", "freeciv-events", "v1")


class TypeGenerationError(ValueError):
    pass


def _pascal(name):
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"[^A-Za-z0-9]+", name) if part)


def _ref_name(ref):
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        raise TypeGenerationError("unsupported external ref: {}".format(ref))
    return _pascal(ref[len(prefix):])


def _literal(value):
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    return json.dumps(value, ensure_ascii=False)


def _type(schema, indent=""):
    if not isinstance(schema, dict):
        raise TypeGenerationError("schema node must be an object")
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "const" in schema:
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    if "oneOf" in schema:
        return " | ".join(_type(item, indent) for item in schema["oneOf"])
    if "anyOf" in schema:
        return " | ".join(_type(item, indent) for item in schema["anyOf"])
    kind = schema.get("type")
    if isinstance(kind, list):
        mapping = {"null": "null", "boolean": "boolean", "number": "number",
                   "integer": "number", "string": "string", "array": "unknown[]",
                   "object": "Record<string, unknown>"}
        try:
            return " | ".join(mapping[item] for item in kind)
        except KeyError as exc:
            raise TypeGenerationError("unsupported union member: {}".format(exc))
    if kind is None:
        if not schema:
            return "unknown"
        raise TypeGenerationError("schema node has no supported type: {}".format(schema))
    if kind == "null":
        return "null"
    if kind == "boolean":
        return "boolean"
    if kind in ("number", "integer"):
        return "number"
    if kind == "string":
        return "string"
    if kind == "array":
        item = _type(schema.get("items", {}), indent)
        return "Array<{}>".format(item)
    if kind == "object":
        return _inline_object(schema, indent)
    raise TypeGenerationError("unsupported schema type: {}".format(kind))


def _inline_object(schema, indent=""):
    properties = schema.get("properties", {})
    required = set(schema.get("required", []))
    lines = ["{"]
    child_indent = indent + "  "
    for name in sorted(properties):
        optional = "" if name in required else "?"
        lines.append("{}{}{}: {};".format(child_indent, json.dumps(name), optional,
                                           _type(properties[name], child_indent)))
    additional = schema.get("additionalProperties", True)
    if additional is True:
        lines.append("{}[key: string]: unknown;".format(child_indent))
    elif isinstance(additional, dict):
        lines.append("{}[key: string]: {};".format(child_indent, _type(additional, child_indent)))
    elif additional is not False:
        raise TypeGenerationError("unsupported additionalProperties: {}".format(additional))
    lines.append(indent + "}")
    return "\n".join(lines)


def _definition(name, schema):
    ts_name = _pascal(name)
    if schema.get("type") == "object" and "oneOf" not in schema and "anyOf" not in schema:
        body = _inline_object(schema)
        return "export type {} = {};".format(ts_name, body)
    return "export type {} = {};".format(ts_name, _type(schema))


def generate(envelope, payloads):
    defs = payloads["$defs"]
    known = [name for name in defs if name in (
        "run_started", "run_completed", "ruleset_compiled", "state_snapshot",
        "observation", "revision", "belief_conflict", "context_quarantine",
        "llm_proposal", "verification", "quarantine",
        "pln_query", "pln_result", "pressure_propagated", "operation_scored",
        "conductance_updated",
        "plan_created", "monitor_trigger",
        "plan_invalidated", "plan_step_executed", "action_sent", "action_result",
        "grounded_check", "metric_sample", "logging_gap")]
    lines = [
        "// Generated by scripts/freeciv/generate_event_types.py. DO NOT EDIT.",
        "// Source: schemas/freeciv-events/v1/*.schema.json",
        "",
        "export const EVENT_SCHEMA_VERSION = \"1.0\" as const;",
        "",
    ]
    for name, value in defs.items():
        lines.append(_definition(name, value))
        lines.append("")
    known_literals = " | ".join(json.dumps(name) for name in known)
    lines.append("export type KnownEventType = {};".format(known_literals))
    lines.append("")
    lines.extend([
        "export interface EventEnvelope<T extends string = string, P extends object = Record<string, unknown>> {",
        "  schema_version: typeof EVENT_SCHEMA_VERSION;",
        "  event_id: string;",
        "  game_id: string;",
        "  turn: number;",
        "  seq: number;",
        "  ts: string;",
        "  type: T;",
        "  caused_by: string[];",
        "  payload: P;",
        "}",
        "",
        "export interface KnownPayloadMap {",
    ])
    for name in known:
        lines.append("  {}: {};".format(json.dumps(name), _pascal(name)))
    lines.extend([
        "}",
        "",
        "export type KnownEvent = {",
        "  [K in KnownEventType]: EventEnvelope<K, KnownPayloadMap[K]>;",
        "}[KnownEventType];",
        "",
        "export type UnknownEvent = EventEnvelope<string, Record<string, unknown>>;",
        "export type FreecivEvent = KnownEvent | UnknownEvent;",
        "",
    ])
    return "\n".join(lines)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=os.path.join(_SCHEMA_DIR, "types.generated.ts"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    envelope = json.load(open(os.path.join(_SCHEMA_DIR, "envelope.schema.json"), encoding="utf-8"))
    payloads = json.load(open(os.path.join(_SCHEMA_DIR, "payloads.schema.json"), encoding="utf-8"))
    result = generate(envelope, payloads)
    if args.check:
        try:
            existing = open(args.out, encoding="utf-8").read()
        except OSError:
            print("generated types missing: {}".format(args.out), file=sys.stderr)
            return 1
        if existing != result:
            print("generated event types are stale: {}".format(args.out), file=sys.stderr)
            return 1
        print("generated event types are current")
        return 0
    parent = os.path.dirname(os.path.abspath(args.out))
    os.makedirs(parent, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as stream:
        stream.write(result)
    print("wrote {}".format(args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
