"""Compatibility facade for grounded Impact planning.

Stable contracts and explicit policy defaults live in :mod:`impact_types`.
The behavior-preserving imperative planner remains in :mod:`impact_legacy`
until the evidence-gated FDAS consolidation audit authorizes domain removal.
"""

from .impact_types import (
    COMMERCE_IMPROVEMENT_PRIORITY,
    DEFENDER_PRIORITY,
    DeferredImpactOutcomeLedger,
    DeferredImpactResolution,
    EXPLORER_TYPES,
    FOOD_OUTPUT_PRIORITY,
    FOOD_STABILIZATION_PRIORITY,
    GroundedGoalRelief,
    HAPPINESS_IMPROVEMENT_PRIORITY,
    IMPROVEMENT_PRIORITY,
    INDUSTRIAL_IMPROVEMENT_PRIORITY,
    ImpactCandidate,
    ImpactDecision,
    ImpactTurnBudget,
    LEGACY_FOUNDER_TYPES,
    NAVAL_IMPROVEMENT_PRIORITY,
    NORMALIZED_COMMERCE_IMPROVEMENT_TYPES,
    NORMALIZED_DEFENDER_TYPES,
    NORMALIZED_FOOD_OUTPUT_TYPES,
    NORMALIZED_HAPPINESS_IMPROVEMENT_TYPES,
    NORMALIZED_TREASURY_STABILIZATION_TYPES,
    OFFENSIVE_ACTIONS,
    PLANNED_PRODUCTION_TYPES,
    RESEARCH_IMPROVEMENT_PRIORITY,
    RULESET_ADD_TO_CITY_FLAG,
    RULESET_FOUNDER_FLAG,
    RULESET_WORKER_FLAG,
    TREASURY_STABILIZATION_PRIORITY,
    normalized_type as _normalized_type,
    spatial_target as _spatial_target,
    target_name as _target_name,
    wrapped_distance as _distance,
)
from .impact_legacy import GroundedImpactPlanner


__all__ = (
    "COMMERCE_IMPROVEMENT_PRIORITY",
    "DEFENDER_PRIORITY",
    "DeferredImpactOutcomeLedger",
    "DeferredImpactResolution",
    "EXPLORER_TYPES",
    "FOOD_OUTPUT_PRIORITY",
    "FOOD_STABILIZATION_PRIORITY",
    "GroundedGoalRelief",
    "GroundedImpactPlanner",
    "HAPPINESS_IMPROVEMENT_PRIORITY",
    "IMPROVEMENT_PRIORITY",
    "INDUSTRIAL_IMPROVEMENT_PRIORITY",
    "ImpactCandidate",
    "ImpactDecision",
    "ImpactTurnBudget",
    "LEGACY_FOUNDER_TYPES",
    "NAVAL_IMPROVEMENT_PRIORITY",
    "NORMALIZED_COMMERCE_IMPROVEMENT_TYPES",
    "NORMALIZED_DEFENDER_TYPES",
    "NORMALIZED_FOOD_OUTPUT_TYPES",
    "NORMALIZED_HAPPINESS_IMPROVEMENT_TYPES",
    "NORMALIZED_TREASURY_STABILIZATION_TYPES",
    "OFFENSIVE_ACTIONS",
    "PLANNED_PRODUCTION_TYPES",
    "RESEARCH_IMPROVEMENT_PRIORITY",
    "RULESET_ADD_TO_CITY_FLAG",
    "RULESET_FOUNDER_FLAG",
    "RULESET_WORKER_FLAG",
    "TREASURY_STABILIZATION_PRIORITY",
)
